apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-deployment
spec:
  selector:
      matchLabels:
        app: flower-service
  replicas: 1
  template:
    metadata:
      labels:
        app: flower-service
    spec:
      containers:
        - name: flower-service
          image: khadijadev/flowers-app:v1.0.0
          imagePullPolicy: Never
          ports:
          - containerPort: 8087
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf 
                  key: host
                  
---

apiVersion: v1
kind: Service
metadata:
  name: flower-service
spec:
  selector:
    app: flower-service
  ports:
    - port: 8087
      protocol: TCP
      nodePort: 30088
  type: LoadBalancer