spring:
  application:
    name: flower-service
  data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'